_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.7
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 53
                - 55
            "2":
                - 1
                - 2
                - 3
                - 5
                - 41
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.7
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
batch_size:
    value: 32
epochs:
    value: 10
name:
    value: mask_detection_v1
project:
    value: mask_detection
shuffle:
    value: true
validation_split:
    value: 0.2
